### ISSUE TITLE
DSQ problems

### ISSUE THREAD

**Issue by rbf660** [boons605/MotoGymkhanaRaceTiming#85]
When sending a DSQ penalty to API the console does not output any confirmation. Apparantly it does process the penalty, because when you send the penalty twice, the system crashes.

2023-11-20 01:06:31,306 [4] WARN  RaceManagement.RaceTracker [(null)] - Received DSQ event for unkown rider d965bc8f-40cc-4519-a34f-d9cf54602a80. Event will be ignored
2023-11-20 01:07:25,989 [4] ERROR RaceManagement.RaceTracker [(null)] - Exception in RaceTracker task: An item with the same key has already been added. Key: b282bc77-3b29-41d3-bf08-fa5d65cecfba
System.ArgumentException: An item with the same key has already been added. Key: b282bc77-3b29-41d3-bf08-fa5d65cecfba
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at RaceManagement.RaceTracker.OnDSQ(DSQEventArgs raceEvent) in C:\Users\pnhil\OneDrive\Documenten\GitHub\MotoGymkhanaRaceTiming\CentralUnit\RaceManagement\RaceTracker.cs:line 441
   at RaceManagement.RaceTracker.<>c__DisplayClass36_0.<Run>b__0() in C:\Users\pnhil\OneDrive\Documenten\GitHub\MotoGymkhanaRaceTiming\CentralUnit\RaceManagement\RaceTracker.cs:line 217

**Comment by CptMalfunction** [comment]
Will be fixing this on Issue 79

**Comment by CptMalfunction** [comment]
The API does not really provide confirmation for any event that you give to it since events are processed seperately from the webserver. So if you get a 200 back that means the event has been received and will be processed when the race tracking code gets to it
